# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=6.3.2.6
last_mod_version=6.3.2.5
group=com.github.wendall911.survivalistessentials

# Common
minecraft_version=26.1.2
mixin_extras_version=0.5.3
whitenoise_version=2.2.1
whitenoise_range=[2.2.1,3.0.0)
fabric_whitenoise_range=[">=2.2.1","<=3.0.0"]
handbook_version=1.3.3
handbook_range=[1.3.3,1.4.0)
fabric_handbook_range=[">=1.3.3","<=1.4.0"]
mixin_version=0.8.5
java_version=25

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.2.43-beta
neoforge_loader_version_range=[11,)
neoforge_version_range=[26.1.2.21-beta,)
neoforge_mc_version_range=[26.1, 26.2)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.148.0+26.1.2
fabric_api_min_version=>=0.143.10
fabric_loader_version=0.19.2
fabric_loader_min_version=>=0.15
fabric_mc_version_range=[">26.1-"]
# https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all
mod_menu_version=18.0.0-alpha.8

# Integration and Testing Mods
# https://www.curseforge.com/minecraft/mc-mods/jei/files/all
jei_version=29.5.0.26
jei_minecraft_version=26.1.2
# https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items/files/all
rei_version=21.11.814
# https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/all
architectury_version=19.0.1
# https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/all
cloth_config_version=26.1.154
ts_version=
mantle_version=
tic_version=
bop_version=
terrablender_version=
glitch_core_version=
byg_version=
tyg_version=
corgilib_version=
geckolib_version=
probe_version=
carryon_fabric_version=7386195
carryon_neoforge_version=7386188
curios_version=
ie_version=
regions_version=
create_neoforge_version=
# https://www.curseforge.com/minecraft/mc-mods/jade/files/all
jade_neoforge_version=7886513
jade_fabric_version=7886518
# https://www.curseforge.com/minecraft/mc-mods/lets-do-beachparty/files/all
letsdo_beach_neoforge_version=
letsdo_beach_fabric_version=
# https://www.curseforge.com/minecraft/mc-mods/lets-do-bloomingnature/files/all
letsdo_blooming_neoforge_version=
letsdo_blooming_fabric_version=
# https://www.curseforge.com/minecraft/mc-mods/lets-do-meadow/files/all
letsdo_meadow_neoforge_version=
letsdo_meadow_fabric_version=
# https://www.curseforge.com/minecraft/mc-mods/lets-do-farm-charm/files/all
letsdo_farm_neoforge_version=
letsdo_farm_fabric_version=
# https://www.curseforge.com/minecraft/mc-mods/lets-do-vinery/files/all
letsdo_vinery_neoforge_version=
letsdo_vinery_fabric_version=
# https://www.curseforge.com/minecraft/mc-mods/lets-do-wildernature/files/all
letsdo_wilder_neoforge_version=
letsdo_wilder_fabric_version=

# Mod options
mod_display_name=Survivalist Essentials
mod_id=survivalistessentials
mod_name=SurvivalistEssentials
mod_author=wendall911
mod_credits=ashar42 billyzekat
license=MIT
mod_description=A small mod to make the first day or two of play more believable. New early game tools, no tree punching, saws, and more!
mod_update_branch=26.1

# CurseForge/Modrinth Options
curseforge_api_key_prop=securseApiKey
curseforge_id=676800
curseforge_slug=survivalist-essentials
modrinth_api_key_prop=modrinthKey
modrinth_id=hFW7KOhm
discord_webhook_prop=seDiscordWebhook
discord_dryrun_webhook_prop=discordDryrunWebhook
release_type=release
release_versions=26.1,26.1.1,26.1.2
