# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=6.2.4.5
last_mod_version=6.2.4.4

# Common
minecraft_version=1.20.1
minecraft_short_version=1.20
whitenoise_version=1.1.1
whitenoise_range=[1.0.0, 2.0.0)
mixin_version=0.8.5
# https://minecraft.wiki/w/Pack_format
pack_format=15
java_version=17

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2023.09.03

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=47.4.8
forge_version_range=[46,)
forge_mc_version_range=[1.20,1.20.2)

# Integration and Testing Mods
# https://www.curseforge.com/minecraft/mc-mods/jei/files/all
jei_version=15.20.0.116
mantle_version=1.11.79
tic_version=3.10.2.92
ts_version=1.20.1-5.0.0.5
bop_version=4617260
terrablender_version=5378180
byg_version=5910111
tyg_version=5630466
corgilib_version=5691268
geckolib_version=4.4.9
probe_version=6106996
carryon_version=4628675
cyanide_version=4584675
patchouli_version=1.20.1-84.1
patchouli_provider_version=1.20.1-1.0.9-Snapshot.1
curios_version=5.14.1
regions_version=5558225
create_forge_version=6641603

# Mod options
mod_display_name=Survivalist Essentials
mod_id=survivalistessentials
mod_name=SurvivalistEssentials
mod_author=wendall911
mod_credits=ashar42 billyzekat
license=MIT
mod_description=A small mod to make the first day or two of play more believable. New early game tools, no tree punching, saws, and more!
mod_update_branch=1.20.1

# CurseForge/Modrinth Options
# Global properties are located in ~/.gradle/gradle.properties
# DO NOT put private keys here
curseforge_api_key_prop=securseApiKey
curseforge_id=676800
curseforge_slug=survivalist-essentials
modrinth_api_key_prop=modrinthKey
modrinth_id=hFW7KOhm
discord_webhook_prop=seDiscordWebhook
discord_dryrun_webhook_prop=discordDryrunWebhook
release_type=release
release_versions=1.20.1
