# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=6.3.1.4
last_mod_version=6.3.1.3

# Common
minecraft_version=1.21.1
mixin_extras_version=0.3.5
whitenoise_version=2.2.0
whitenoise_range=[2.2.0,3.0.0)
fabric_whitenoise_range=[">=2.2.0","<=3.0.0"]
handbook_version=1.2.3
mixin_version=0.8.5
# https://minecraft.wiki/w/Pack_format
pack_format=34
java_version=21

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2024.11.17

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.1.209
neoforge_loader_version_range=[4,)
neoforge_mc_version_range=[1.21.1, 1.21.2)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.116.6+1.21.1
fabric_loader_version=0.17.2
fabric_loader_min_version=>=0.15
fabric_mc_version_range=["=1.21.1"]
# https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all
mod_menu_version=11.0.3

# Integration and Testing Mods
# https://www.curseforge.com/minecraft/mc-mods/jei/files/all
jei_version=19.25.0.321
# https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items/files/all
rei_version=16.0.799
# https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/all
architectury_version=13.0.8
# https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/all
cloth_config_version=15.0.140
ts_version=6.+
mantle_version=1.11.+
tic_version=3.9.+
bop_version=5489686
terrablender_version=5864140
glitch_core_version=5483773
byg_version=5894952
tyg_version=5691181
corgilib_version=5691275
geckolib_version=4.7
probe_version=12.0.3-5
carryon_fabric_version=5649345
carryon_neoforge_version=5649344
curios_version=9.5.1
trinkets_version=3.10.0
ie_version=5828000
regions_version=5579932
create_neoforge_version=6641610
# https://www.curseforge.com/minecraft/mc-mods/lets-do-beachparty/files/all
letsdo_beach_neoforge_version=7116291
letsdo_beach_fabric_version=7116293
# https://www.curseforge.com/minecraft/mc-mods/lets-do-bloomingnature/files/all
letsdo_blooming_neoforge_version=7106529
letsdo_blooming_fabric_version=7106552
# https://www.curseforge.com/minecraft/mc-mods/lets-do-meadow/files/all
letsdo_meadow_neoforge_version=7103342
letsdo_meadow_fabric_version=7103346
# https://www.curseforge.com/minecraft/mc-mods/lets-do-farm-charm/files/all
letsdo_farm_neoforge_version=7081972
letsdo_farm_fabric_version=7081974
# https://www.curseforge.com/minecraft/mc-mods/lets-do-vinery/files/all
letsdo_vinery_neoforge_version=7129943
letsdo_vinery_fabric_version=7143965
# https://www.curseforge.com/minecraft/mc-mods/lets-do-wildernature/files/all
letsdo_wilder_neoforge_version=6986772
letsdo_wilder_fabric_version=7053529

# Mod options
mod_display_name=Survivalist Essentials
mod_id=survivalistessentials
mod_name=SurvivalistEssentials
mod_author=wendall911
mod_credits=ashar42 billyzekat
license=MIT
mod_description=A small mod to make the first day or two of play more believable. New early game tools, no tree punching, saws, and more!
mod_update_branch=1.21.1

# CurseForge/Modrinth Options
curseforge_api_key_prop=securseApiKey
curseforge_id=676800
curseforge_slug=survivalist-essentials
modrinth_api_key_prop=modrinthKey
modrinth_id=hFW7KOhm
discord_webhook_prop=seDiscordWebhook
discord_dryrun_webhook_prop=discordDryrunWebhook
release_type=release
release_versions=1.21.1
