modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${license}"
issueTrackerURL="https://github.com/${mod_author}/${mod_name}/issues"
[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_name}"
    updateJSONURL="https://raw.githubusercontent.com/${mod_author}/${mod_name}/${mod_update_branch}/files/updates.json"
    displayURL="https://github.com/${mod_author}/${mod_name}"
    logoFile="${mod_id}_icon.png"
    authors="${mod_author}"
    credits="${mod_credits}"
    description='''
    ${mod_description}
    '''
[[mixins]]
    config = "${mod_id}.mixins.json"
[[mixins]]
    config = "${mod_id}.neoforge.mixins.json"
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${neoforge_mc_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="whitenoise"
    type="required"
    versionRange="${whitenoise_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="handbook"
    type="required"
    versionRange="${handbook_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="fruitfulfun"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="quark"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="biomesoplenty"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="allyoucaneat"
    type="optional"
    versionRange="[0,]"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="watersource"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="sushigocrafting"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="botania"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="immersiveengineering"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="ars_nouveau"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="geckolib3"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="undergarden"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="biomeswevegone"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="twilightforest"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="ecologics"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="aquaculture"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="malum"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="iceandfire"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="regions_unexplored"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="beachparty"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="bloomingnature"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="meadow"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="vinery"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
